<a href="https://colab.research.google.com/github/Solsmi/challenge_telecomx_latam2/blob/main/Challenge2_TelecomX_LATAM_.ipynb" target="_parent"><img src="https://colab.research.google.com/assets/colab-badge.svg" alt="Open In Colab"/></a>

#TelecomX Challenge 2

##📌 Extracción

In [31]:
import pandas as pd
import seaborn as sns
import matplotlib.pyplot as plt

In [32]:
df = pd.read_csv('/content/datos_tratados.csv')
df.head()

,CustomerID,Churn,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,ChargesDaily,ChargesMonthly,ChargesTotal
0,0002-ORFBO,No,Female,No,Yes,Yes,9,Yes,No,DSL,...,No,Yes,Yes,No,One year,Yes,Mailed check,2.19,65.6,593.30
1,0003-MKNFE,No,Male,No,No,No,9,Yes,Yes,DSL,...,No,No,No,Yes,Month-to-month,No,Mailed check,2.00,59.9,542.40
2,0004-TLHLJ,Yes,Male,No,No,No,4,Yes,No,Fiber optic,...,Yes,No,No,No,Month-to-month,Yes,Electronic check,2.46,73.9,280.85
3,0011-IGKFF,Yes,Male,Yes,Yes,No,13,Yes,No,Fiber optic,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,3.27,98.0,1237.85
4,0013-EXCHZ,Yes,Female,Yes,Yes,No,3,Yes,No,Fiber optic,...,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,2.80,83.9,267.40

In [33]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 7043 entries, 0 to 7042
Data columns (total 22 columns):
 #   Column            Non-Null Count  Dtype
---  ------            --------------  -----
 0   CustomerID        7043 non-null   object
 1   Churn             7043 non-null   object
 2   Gender            7043 non-null   object
 3   SeniorCitizen     7043 non-null   object
 4   Partner           7043 non-null   object
 5   Dependents        7043 non-null   object
 6   Tenure            7043 non-null   int64
 7   PhoneService      7043 non-null   object
 8   MultipleLines     7043 non-null   object
 9   InternetService   7043 non-null   object
 10  OnlineSecurity    7043 non-null   object
 11  OnlineBackup      7043 non-null   object
 12  DeviceProtection  7043 non-null   object
 13  TechSupport       7043 non-null   object
 14  StreamingTV       7043 non-null   object
 15  StreamingMovies   7043 non-null   object
 16  Contract          7043 non-null   object
 17  PaperlessBilling  7043 non-null   object
 18  PaymentMethod     7043 non-null   object
 19  ChargesDaily      7043 non-null   float64
 20  ChargesMonthly    7043 non-null   float64
 21  ChargesTotal      7043 non-null   float64
dtypes: float64(3), int64(1), object(18)
memory usage: 1.2+ MB

###Verificación valores nulos

In [34]:
df.isnull().sum()

CustomerID          0
Churn               0
Gender              0
SeniorCitizen       0
Partner             0
Dependents          0
Tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
ChargesDaily        0
ChargesMonthly      0
ChargesTotal        0
dtype: int64

###Verificación valores con espacios vacíos o en blanco

In [35]:
df.apply(lambda x: x.astype(str).str.strip() == '').sum()

CustomerID          0
Churn               0
Gender              0
SeniorCitizen       0
Partner             0
Dependents          0
Tenure              0
PhoneService        0
MultipleLines       0
InternetService     0
OnlineSecurity      0
OnlineBackup        0
DeviceProtection    0
TechSupport         0
StreamingTV         0
StreamingMovies     0
Contract            0
PaperlessBilling    0
PaymentMethod       0
ChargesDaily        0
ChargesMonthly      0
ChargesTotal        0
dtype: int64

In [36]:
object_columns = df.select_dtypes(include='object').columns

for col in object_columns:
    print(f"Column: {col}")
    value_counts = df[col].value_counts()
    print(value_counts)

    # destacar valores vacios o espacios en blanco
    empty_values_count = df[col].apply(lambda x: isinstance(x, str) and x.strip() == '').sum()
    if empty_values_count > 0:
        print(f"\033[1m    (Observacion: Se encontraron {empty_values_count} valores vacíos o de solo espacios en blanco)\033[0m") # ANSI escape codes for bold text

    print("\n" + "-" * 30 + "\n")

Column: CustomerID
CustomerID
9995-HOTOH    1
0002-ORFBO    1
0003-MKNFE    1
9970-QBCDA    1
9968-FFVVH    1
             ..
0014-BMAQU    1
0013-SMEOE    1
0013-MHZWF    1
0013-EXCHZ    1
0011-IGKFF    1
Name: count, Length: 7043, dtype: int64

------------------------------

Column: Churn
Churn
No     5174
Yes    1869
Name: count, dtype: int64

------------------------------

Column: Gender
Gender
Male      3555
Female    3488
Name: count, dtype: int64

------------------------------

Column: SeniorCitizen
SeniorCitizen
No     5901
Yes    1142
Name: count, dtype: int64

------------------------------

Column: Partner
Partner
No     3641
Yes    3402
Name: count, dtype: int64

------------------------------

Column: Dependents
Dependents
No     4933
Yes    2110
Name: count, dtype: int64

------------------------------

Column: PhoneService
PhoneService
Yes    6361
No      682
Name: count, dtype: int64

------------------------------

Column: MultipleLines
MultipleLines
No     4072
Yes    2971
Name: count, dtype: int64

------------------------------

Column: InternetService
InternetService
Fiber optic    3096
DSL            2421
No             1526
Name: count, dtype: int64

------------------------------

Column: OnlineSecurity
OnlineSecurity
No     5024
Yes    2019
Name: count, dtype: int64

------------------------------

Column: OnlineBackup
OnlineBackup
No     4614
Yes    2429
Name: count, dtype: int64

------------------------------

Column: DeviceProtection
DeviceProtection
No     4621
Yes    2422
Name: count, dtype: int64

------------------------------

Column: TechSupport
TechSupport
No     4999
Yes    2044
Name: count, dtype: int64

------------------------------

Column: StreamingTV
StreamingTV
No     4336
Yes    2707
Name: count, dtype: int64

------------------------------

Column: StreamingMovies
StreamingMovies
No     4311
Yes    2732
Name: count, dtype: int64

------------------------------

Column: Contract
Contract
Month-to-month    3875
Two year          1695
One year          1473
Name: count, dtype: int64

------------------------------

Column: PaperlessBilling
PaperlessBilling
Yes    4171
No     2872
Name: count, dtype: int64

------------------------------

Column: PaymentMethod
PaymentMethod
Electronic check             2365
Mailed check                 1612
Bank transfer (automatic)    1544
Credit card (automatic)      1522
Name: count, dtype: int64

------------------------------

##🛠️ Pre procesamiento

###Eliminar columnas irrelevantes

In [37]:
df = df.drop(columns=['CustomerID'])    #eliminar columna CustomerID
df

,Churn,Gender,SeniorCitizen,Partner,Dependents,Tenure,PhoneService,MultipleLines,InternetService,OnlineSecurity,...,DeviceProtection,TechSupport,StreamingTV,StreamingMovies,Contract,PaperlessBilling,PaymentMethod,ChargesDaily,ChargesMonthly,ChargesTotal
0,No,Female,No,Yes,Yes,9,Yes,No,DSL,No,...,No,Yes,Yes,No,One year,Yes,Mailed check,2.19,65.60,593.30
1,No,Male,No,No,No,9,Yes,Yes,DSL,No,...,No,No,No,Yes,Month-to-month,No,Mailed check,2.00,59.90,542.40
2,Yes,Male,No,No,No,4,Yes,No,Fiber optic,No,...,Yes,No,No,No,Month-to-month,Yes,Electronic check,2.46,73.90,280.85
3,Yes,Male,Yes,Yes,No,13,Yes,No,Fiber optic,No,...,Yes,No,Yes,Yes,Month-to-month,Yes,Electronic check,3.27,98.00,1237.85
4,Yes,Female,Yes,Yes,No,3,Yes,No,Fiber optic,No,...,No,Yes,Yes,No,Month-to-month,Yes,Mailed check,2.80,83.90,267.40
...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...,...
7038,No,Female,No,No,No,13,Yes,No,DSL,Yes,...,No,Yes,No,No,One year,No,Mailed check,1.84,55.15,742.90
7039,Yes,Male,No,Yes,No,22,Yes,Yes,Fiber optic,No,...,No,No,No,Yes,Month-to-month,Yes,Electronic check,2.84,85.10,1873.70
7040,No,Male,No,No,No,2,Yes,No,DSL,No,...,No,No,No,No,Month-to-month,Yes,Mailed check,1.68,50.30,92.75
7041,No,Male,No,Yes,Yes,67,Yes,No,DSL,Yes,...,Yes,Yes,No,Yes,Two year,No,Mailed check,2.26,67.85,4627.65
7042,No,Male,No,Yes,Yes,63,No,No,DSL,Yes,...,Yes,No,Yes,Yes,Two year,No,Electronic check,1.97,59.00,3707.60